### ISSUE TITLE
'Integration not found' but is here !

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [tykarol/home-assistant-xjx-toilet-pro#2]
Hi,

Foremost, thank you for your great work !

Then, it's late, so let's cut the details (will come back later for them, as an edit);

I've this toilet, which should be the one you're supporting in this HA integration : 
![image](https://user-images.githubusercontent.com/8619233/169912232-adc4fa41-9977-407e-9499-38203b77ebe0.png)

Installation successful : 
![image](https://user-images.githubusercontent.com/8619233/169911767-b94e0472-aed5-4367-91f1-7b3b9ccf2fe7.png)
![image](https://user-images.githubusercontent.com/8619233/169912341-dbfcdc5b-dd1c-47b5-975a-c5b6af1948ad.png)
![image](https://user-images.githubusercontent.com/8619233/169912409-bdca2530-3fb4-48b4-a9fd-662c1b8d55e4.png)
![image](https://user-images.githubusercontent.com/8619233/169912647-4c8e28ff-2de7-4ecd-9cbc-ef09e6b2edfb.png)

But, following errors : 
![image](https://user-images.githubusercontent.com/8619233/169911909-cfaa94f3-0a7c-4ff4-bcc5-8be15c2f217f.png)
![image](https://user-images.githubusercontent.com/8619233/169911937-437a759e-75c4-46f9-b9a5-9f021630e721.png)
--> And no toilet sensor found !

Content of `cat configuration.yaml` :
```yaml
toiletlid:
  - platform: xjx_toilet_pro
    host: 192.168.1.xx
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    name: 'Xiaomi Whale Smart Toilet Cover'
```
